#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


std::string solve(int64_t X) {
    // TODO: edit here
    if (X >= 90)
        cout << "expert" << endl;
    else if (X >= 70)
        cout << 90 - X << endl;
    else if (X >= 40)
        cout << 70 - X << endl;
    else
        cout << 40 - X << endl;
    return "";
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t X;
    std::cin >> X;
    auto ans = solve(X);
    // std::cout << ans << '\n';
    return 0;
}
